name: check_ipos

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '15 18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run IPO tracking
        env:
          TODOIST_APIKEY: ${{ secrets.TODOIST_APIKEY }}
        run: |
          python ipo.py
      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "ipo-bot@example.com"
          git config --global user.name "IPO-bot"
          git diff --quiet || (git add ipo.json && git commit -m "Updated with latest IPOs")
          git push origin HEAD:main
